routes/admin.php
<?php



Voyager::routes();

Route::get('/cars/calendar/{car}', 'CarController@calendar')->name('voyager.cars.calendar');

Route::get('/update/currency', 'CurrencyController@updateCurrency')->name('currency.update');
Route::get('/update/currency', 'CurrencyController@updateCurrency')->name('currency.update');
Route::get('/profile/confirmation', 'CurrencyController@saveCurrency')->name('currency.save');

Route::post('/profile/status/{id}', 'ProfileController@updateStatus')->name('profile.status');

Route::get('/cars-status/{car}/{status}', 'CarController@updateStatus')->name('voyager.cars.status');

Route::get('/user-block/{user}/{status}', 'UserController@block')->name('voyager.users.block');

Route::post('car-wrong-fill/{car}', 'CarController@wrongFill')->name('voyager.cars.wrong-fill');

//Route::get('/templates/{template}', function ($template){
//    return view('templates.'.$template);
//});

Route::get('orders/{order}/{act}', 'OrderController@sendResponse')->name('admin.orders.send_response');


// REOLY TICKETS

Route::post('ticket-reply/{ticket}', 'TicketController@reply')->name('admin.ticket.reply');

// NOTIFY

Route::get('car-notify', 'NotificationController@carChange')->name('admin.car-change.notify');
Route::get('owner-profile-notify', 'NotificationController@ownerProfileChange')->name('admin.owner-profile-change.notify');

// OWNER PROFILE

Route::get('check-owner-profile/{profile}', 'OwnerProfileController@checkProfile')->name('admin.check-owner-profile');

Route::post('send-user-email', 'UserController@sendUserEmail')->name('admin.send_user_email');

Route::get('tickets/close/{ticket}', 'ticketController@close')->name('voyager.tickets.close');

Route::get('car/history/{car}', 'CarController@showHistory')->name('voyager.cars.history.show');

//Route::post('cars', function()
//{
//    dd(($_SERVER["CONTENT_LENGTH"]));
//    if (isset($_SERVER["CONTENT_LENGTH"])
//        && ($_SERVER["CONTENT_LENGTH"]>((int)ini_get('post_max_size')*1024*1024)))
//    {
//        throw new PostSizeExceededException();
//    }
//})->name('voyager.cars.store');

routes/web.php
<?php

use Illuminate\Support\Str;
use Spatie\Sitemap\SitemapGenerator;
use Spatie\Sitemap\Tags\Url;


Route::group(['middleware' => 'verified'], function () {

    Route::get('/index.html', 'HomeController@index');
    Route::get('/index.php', 'HomeController@index');
    Route::get('/index', 'HomeController@index');
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['prefix' => 'profile', 'middleware' => ['auth', 'verified', 'user']], function () {
        Route::get('/', 'User\UserController@index')->name('profile');
        Route::get('/edit', 'User\UserController@edit')->name('profile.edit');
        Route::post('/update', 'User\UserController@update')->name('profile.update');
        Route::post('/password', 'User\UserController@password')->name('profile.password');
        Route::post('/ajax-upload', 'User\UserController@ajaxUpload')->name('profile.ajax');
        Route::get('/states/{code?}', 'User\UserController@getStates')->name('profile.states');

        Route::get('/history', 'User\ProfileController@history')->name('profile.history');
        Route::get('/favorites', 'User\ProfileController@favorites')->name('profile.favorites');
        // PROFILE POSTS

        Route::resource('/posts', 'User\PostController');
        Route::post('/posts/upload', 'User\PostController@upload')->name('posts.upload');

        Route::get('/action-favorite/{car}', 'User\UserController@actionFavorite')->name('profile.action-favorite');

        Route::get('/check-profile', 'User\UserController@checkProfile')->name('profile.check');
        Route::get('/edit-profile-pasport-images/{profile}', 'User\UserController@pasportImages')->name('profile.posport_images');
        Route::get('/check-profile-dock/{profile}', 'User\UserController@checkProfileDock')->name('profile.check_doc');

        Route::get('order/{order}', 'User\OrderController@getOrder')->name('user.order.get');
        Route::post('order/cancel/{order}', 'User\OrderController@cancel')->name('user.order.cancel');

        Route::post('make-review/{car}', 'User\UserController@makeReview')->name('user.review.make');

        Route::delete('delete/{user}', 'User\UserController@deleteProfile')->name('user.delete_profile');
    });
// home posts
    Route::get('post_in_home/{width?}', 'HomeController@getPost')->name('post_in_home');


    Route::match(['get', 'post'], '/search/{location?}', 'CarController@index')->name('search');
// post routes
    Route::get('/posts', 'PostsController@index')->name('posts');
    Route::get('/posts/{slug}', 'PostsController@show')->name('post.single');

//faq routes
    Route::get('/faq/{for_whom?}/{cat?}/{question?}', 'FaqsController@index')->name('faq');
    Route::get('/faq/unlike/like/{faq}/{like}', 'FaqsController@like')->name('faq.like')->middleware('auth');

    //page routes

    Route::get('/pages/{slug?}', 'PagesController@index')->name('pages');
    Route::get('/for-whom', 'PagesController@forWhom')->name('for-whom');
    Route::get('/for-car-owner/{slug?}', 'PagesController@forWhomOwner')->name('pages.for_whom_owner');
    Route::get('/for-tenants/{slug?}', 'PagesController@forTenants')->name('pages.for_tenants');
    Route::get('/insurance/{slug?}', 'PagesController@insurance')->name('pages.insurance');


    Route::get('page/get-document/{page}', 'PagesController@getDocument')->name('page.getDocument');


    Route::get('/car/{slug}', 'CarController@show')->name('car.single');
    Route::get('/car', function () {
        return redirect()->route('search');
    });
    Route::match(['GET', 'POST'], '/car/get-prices/{car}/{barcode?}', 'CarController@getPrices')->name('car.get_prices');
    Route::get('/similar-cars/{car}', 'CarController@similarCars')->name('car.similar');


//COMMENT

    Route::get('get-comments/{model}/{item}', 'CommentsController@index')->name('comments');
    Route::group(['middleware' => 'auth'], function () {
        Route::post('comments', 'CommentsController@store');
        Route::delete('comments/{comment}', 'CommentsController@destroy');
        Route::put('comments/{comment}', 'CommentsController@update');
        Route::post('comments/{comment}', 'CommentsController@reply');
    });


    Route::get('/currency/{currency}', 'CurrencyController@setCurrency')->name('currency.change');

    //CONTACT US

    Route::get('/contact-us', 'HomeController@contact')->name('contact_us');

    Route::post('contact-us', 'HomeController@contactUsPost')->name('contact_us.store');


//    Paynebt return url

    Route::get('/payment/{status}', 'User\PaymentController@paymentResponse')->name('payment.response');
    Route::get('/payment/get-order-status/{order}', 'User\PaymentController@orderStatus')->name('payment.order_status');
    Route::get('/full-pay/{order}', 'User\PaymentController@fullPay')->name('user.full_pay');


});

// GET ALL CARS FOR MAP

Route::get('get-all-cars', 'CarController@getAllCars')->name('car.get-all');

Route::get('robots.txt', 'RobotsController@__invoke');

//Route::get('/sitemap', function () {
//    SitemapGenerator::create(config('app.url'))
//        ->hasCrawled(function (Url $url) {
//            if (Str::contains($url->url, [
//                    '/admin',
//                    '/public/',
//                    '/profile',
//                    '/currency',
//                    '/auth',
//                    '/login',
//                    '/register',
//                    '/password',
//                    '/c-owner',
//                    '/posts?slug',
//                    '/ru/',
//                    '/en/',
//                    '/storage/',
//                    '/search?date'
//                ]) || ($url->segment(1) === 'en' && !$url->segment(2)) || $url->segment(1) === 'ru') {
//                return;
//            }
//            if ($url->segment(1) === 'en') {
//                $url->addAlternate($url->url, 'en');
//            } else {
//                $url->url = LaravelLocalization::getLocalizedURL('ru', $url->url);
//                if ($url->segment(1) == 'faq') {
//                    $url->setPriority(0.6);
//                } elseif ($url->segment(1) == 'car') {
//                    $url->setPriority(0.4);
//                } elseif ($url->segment(1) == 'search') {
//                    $url->setPriority(0.3);
//                } elseif ($url->segment(1) == 'pages') {
//                    $url->setPriority(0.2);
//                } elseif ($url->segment(1) == 'posts') {
//                    $url->setPriority(0.5);
//                } elseif (!$url->segment(1)) {
//                    $url->setPriority(1);
//                }
//            }
//            return $url;
////                return !strpos($url->getPath(), '/admin/') ||
////                    !strpos($url->getPath(), '/public/') ||
////                    !strpos($url->getPath(), '/profile/') ||
////                    !strpos($url->getPath(), '/c-owner/') ||
////                    !strpos($url->getPath(), '/currency/') ||
////                    !strpos($url->getPath(), '/auth/') ||
////                    !strpos($url->getPath(), '/login') ||
////                    !strpos($url->getPath(), '/register') ||
////                    !strpos($url->getPath(), '/password/') ||
////                    !strpos($url->getPath(), '/images/') ||
////                    !strpos($url->getPath(), '/posts?slug');
//
//        })
//        ->setChangeFrequency(Url::CHANGE_FREQUENCY_WEEKLY)->writeToFile('sitemap.xml');
//
//    return 'site map created';
//});

//Route::get('/config-clear', function () {
//    \Illuminate\Support\Facades\Artisan::call('config:clear');
//    return back();
//});
Auth::routes(['verify' => true]);
Route::post('guest-reg/{car}', 'Auth\RegisterController@guestReg')->name('auth.guest_reg')->middleware('guest');

// OAuth Routes
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/logout', 'Auth\AuthController@logout')->name('logout')->middleware('auth');

Route::get('get-translate/y/{word?}', 'TranslateController@getTranslate');

Route::get('images/{w?}_{h?}_{q?}/{encode}/{src}', 'ImageController@getCacheImage')->name('get-image');

Route::post('/push', 'PushController@store');
//Route::get('/push','PushController@push')->name('push');

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Voyager\VoyagerBaseController;
use App\Models\Tag;
use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Events\BreadDataAdded;
use TCG\Voyager\Events\BreadDataUpdated;
use Illuminate\Database\Eloquent\SoftDeletes;

class PostController extends VoyagerBaseController
{
    public function update(Request $request, $id)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Compatibility with Model binding.
        $id = $id instanceof Model ? $id->{$id->getKeyName()} : $id;

        $model = app($dataType->model_name);
        if ($dataType->scope && $dataType->scope != '' && method_exists($model, 'scope'.ucfirst($dataType->scope))) {
            $model = $model->{$dataType->scope}();
        }
        if ($model && in_array(SoftDeletes::class, class_uses($model))) {
            $data = $model->withTrashed()->findOrFail($id);
        } else {
            $data = call_user_func([$dataType->model_name, 'findOrFail'], $id);
        }

        // Check permission
        $this->authorize('edit', $data);

        // Validate fields with ajax
        $val = $this->validateBread($request->all(), $dataType->editRows, $dataType->name, $id)->validate();
        $data = $this->insertUpdateData($request, $slug, $dataType->editRows, $data);
        $data->tags()->delete();
        $tags = explode('#', $request->tags);
        foreach($tags as $tag){
            if (trim($tag)){
                $attachTag = Tag::where('name', trim($tag))->first();
                if (!$attachTag){
                    $attachTag = new Tag();
                    $attachTag->name = $tag;
                    $attachTag->save();
                }
                $data->tags()->attach($attachTag->id);
            }
        }
        event(new BreadDataUpdated($dataType, $data));

        return redirect()
            ->route("voyager.{$dataType->slug}.index")
            ->with([
                'message'    => __('voyager::generic.successfully_updated')." {$dataType->display_name_singular}",
                'alert-type' => 'success',
            ]);
    }


    public function store(Request $request)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Check permission
        $this->authorize('add', app($dataType->model_name));

        // Validate fields with ajax
        $val = $this->validateBread($request->all(), $dataType->addRows)->validate();
        $data = $this->insertUpdateData($request, $slug, $dataType->addRows, new $dataType->model_name());

        $data->tags()->delete();
        $tags = explode('#', $request->tags);
        foreach($tags as $tag){
            if (trim($tag)){
                $attachTag = Tag::where('name', trim($tag))->first();
                if (!$attachTag){
                    $attachTag = new Tag();
                    $attachTag->name = $tag;
                    $attachTag->save();
                }
                $data->tags()->attach($attachTag->id);
            }
        }

        event(new BreadDataAdded($dataType, $data));

        return redirect()
            ->route("voyager.{$dataType->slug}.index")
            ->with([
                'message'    => __('voyager::generic.successfully_added_new')." {$dataType->display_name_singular}",
                'alert-type' => 'success',
            ]);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Voyager\VoyagerUserController;
use App\Mail\AdminUserSendEmail;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class UserController extends VoyagerUserController
{



    public function block(Request $request, User $user)
    {
        $this->authorize('block', app(User::class));
        $user->block = ($request->status == 'block' ? 1 : 0);
        $user->save();
        $data = $user->block == 1
            ? [
                'message' => 'Пользователь '.$user->fullName.' заблокирован',
                'alert-type' => 'warning',
            ]
            : [
                'message' => 'Пользователь '.$user->fullName.' разблокирован ',
                'alert-type' => 'success',
            ];
        return back()->with($data);
    }

    public function sendUserEmail(Request $request)
    {
        Mail::to($request->to)->send(new AdminUserSendEmail($request->all()));

        return response()->json(['success' => true, 'status' => 'Письмо успешно отправлен ']);
    }


}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\Tag;

class PostsController extends Controller
{
    /*
     * returns posts list
     */
    public function index(Request $request)
    {
        //get posts with relation
        $otherPosts = false;
        $posts = Post::with('tags')
            ->whereTranslation("title", "LIKE", "%" . $request->search . "%")
            ->where(function ($query) use ($request) {
                if ($request->slug) {
                    {
                        $query->whereHas('tags', function ($q) use ($request) {
                            $q->where('tags.slug', $request->slug);
                        });
                    }
                }
            })->orderBy('created_at', 'desc')->orderBy('updated_at', 'desc')->published()->paginate(10);
        $selected_tag = '';
        if ($request->slug) {
            {
                if ($selected_tag = Tag::where('slug', $request->slug)->first()) {
                    $selected_tag->increment('rating');
                }else{
                    return redirect()->route('posts');
                }
            }
        }

        if (!$posts->count()){
            $otherPosts = Post::with('tags')
                ->whereTranslation("title", "LIKE", "%" . $request->search . "%")
                ->limit(10)->get();
            if (!$otherPosts->count()){
                $otherPosts = Post::with('tags')
                    ->limit(10)->get();
            }
        }

        //get all tags
        $tags = Tag::orderBy('rating', 'desc')->where('id', '!=', ($selected_tag ? $selected_tag->id : ''))->get();
        //
        $posts->appends([
            'search' => $request->search,
            'slug' => $request->slug,
        ]);

        if ($request->ajax()) {
            $html = view('posts.post-list', compact('posts'))->render();
            return response()->json(['html' => $html], 200);
        }
        return view('posts.index', compact('posts', 'tags', 'selected_tag', 'otherPosts'));
    }

    /*
     * post single page
     *
     */
    public function show($slug)
    {
        $post = Post::where('slug', $slug)->first();
        if (!$post) abort(404);
        return view('posts.show', compact('post'));

    }

}

resources/views/user/posts/index.blade.php
@extends('layouts.app')
@section('meta')
    @parent
    {!! Robots::metaTag() !!}
@stop
@section('css')

@stop

@section('content')

    <div class="own-container ">
        <div class="row bg-white shadow py-4 mb-4 mt-4 align-items-center">

            <!-- edit form column -->
            <div class="col-md-12  ff-st row ">
                <div class="col-sm-4 mb-3">
                    <a href="{{url()->previous()}}" class="btn own-btn ora   d-inline-block  border-radius-20"
                       title="{{__('general.back')}}">
                        <i class="fas fa-arrow-left"></i>
                        <span class="">{{__('general.back')}}</span>
                    </a>
                </div>
                <div class="col-sm-4 mb-3">
                    <h1 class="text-center">{{__('user.posts')}}</h1>
                </div>
                <div class="col-sm-4 mb-3 text-right">
                    <a href="{{route('posts.create')}}" class="btn btn-primary   d-inline-block  border-radius-20"
                       title="{{__('user_post.add')}}">
                        <i class="fas fa-plus"></i>
                        <span class="">{{__('user_post.add')}}</span>
                    </a>
                </div>

                <div class="own-container bg-white border-radius-20 p-5">
                    <div class="row">
                        <!-- Blog Entries Column -->
                        <div class="col-md-12 order-md-1 order-2">
                            <div class="post-content row" id="blog">
                                @foreach($posts as $post)
                                    <div class="card border-0 shadow mb-5 border-radius-20">
                                        <div class="card-body p-3">
                                            <div class="row">
                                                <div class="col-12 d-flex justify-content-between">
                                                    <div class="">
                                                        @if(isset($post->status) && $post->status == 'PUBLISHED')
                                                            <span
                                                                class="badge badge-success">{{ __('voyager::post.status_published') }}</span>
                                                        @endif
                                                        @if(isset($post->status) && $post->status == 'DRAFT')
                                                            <span
                                                                class="badge badge-secondary">{{ __('voyager::post.status_draft') }}</span>
                                                        @endif
                                                        @if(isset($post->status) && $post->status == 'PENDING')
                                                            <span
                                                                class="badge badge-primary">{{ __('voyager::post.status_pending') }}</span>
                                                        @endif
                                                    </div>
                                                    <div class="">
                                                        <a title="{{__('user_post.edit')}}"
                                                           href="{{route('posts.edit', $post)}}">
                                                            <span><i class="fas fa-edit fa-2x"></i></span>
                                                        </a>
                                                    </div>
                                                </div>
                                                <div
                                                    class="col-md-4 d-flex align-items-center justify-content-center flex-column">
                                                    <img class="img-fluid w-100 border-radius-20"
                                                         src="{{asset("storage/".($post->image ?? 'posts/default.jpg'))}}"
                                                         alt="{{$post->translate()->title}}">
                                                </div>

                                                <div class="col-12 col-md-8">
                                                    <div class="row  mt-3 ">
                                                        <div class="col-12">
                                                            <h4 class="card-title">
                                                                <a href="{{route('post.single', ['slug' => $post->slug])}}">{!! strip_tags($post->translate()->title) !!}</a>
                                                            </h4>
                                                            @if ($post->updated_at->diffInHours($post->created_at) > 24)
                                                                <div class="small text-muted mb-3"><span>{{__('post.updated')}}:</span><span
                                                                        class="pl-2">{{$post->updated_at->format('Y-m-d')}}</span>
                                                                </div>
                                                            @else
                                                                <div
                                                                    class="small text-muted mb-3">{{$post->created_at->format('Y-m-d')}}</div>
                                                            @endif
                                                        </div>

                                                        <div class="author d-flex  col-12 mb-3">
                                                            <div class="avatar mr-3"
                                                                 style="background-image: url({{Voyager::image($post->authorId->avatar)}})">

                                                            </div>
                                                            <div>
                                <span
                                    class="text-default">{{$post->authorId->first_name.' '. $post->authorId->last_name}}</span>
                                                                <small
                                                                    class="d-block text-muted">{{__('role.'.$post->authorId->role->name)}}</small>
                                                            </div>
                                                        </div>

                                                    </div>
                                                    <div class="row">
                                                        <div class="col-12 ff-ms">
                                                            <p class="mb-4">
                                                                {{$post->translate()->excerpt}}
                                                                <a href="{{route('post.single', ['slug' => $post->slug])}}"
                                                                   class="d-inline-block read-post">
                                                                    {{__('post.read_article')}} →
                                                                </a>
                                                            </p>
                                                        </div>

                                                        <div class="col-12 text-center">
                                                            <ul class="list-unstyled mb-0 d-flex flex-wrap">
                                                                @if(isset($selected_tag) && $selected_tag)
                                                                    <li class="tag ">
                                                                        <a href="{{route('posts', ['slug' => $selected_tag->slug])}}"
                                                                           class="badge badge-secondary selected-tag">
                                                                            {{$selected_tag->name}}
                                                                        </a>
                                                                    </li>
                                                                @endif
                                                                @foreach($post->tags->where('id', '!=', (isset($selected_tag) && $selected_tag? $selected_tag->id:''))->sortByDesc('rating')->slice(0, 4) as $tag)
                                                                    <li class="tag ">
                                                                        <a href="{{route('posts', ['slug' => $tag->slug])}}"
                                                                           class="badge badge-secondary  ">{{$tag->name}}</a>
                                                                    </li>
                                                                @endforeach
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach

                                <div class="post-paginate">
                                    <!-- Pagination -->
                                    {{$posts->links()}}

                                </div>
                            </div>
                            <!-- Blog Post -->
                        </div>
                    </div>
                    <!-- /.container -->
                </div>

            </div>

        </div>
    </div>
@endsection

@section('script')

@stop